HW3
made-mlops-2022/alexander_gerasimov pull request #5
Opened 2022-11-28 23:05 UTC by AlexG888

Main part:
- Implemented dag that generates data for model training
- Implemented dag that trains the model on a weekly basis using the current day's data
- Implemented dag that uses the model on a daily basis
* all dags are implemented only with the help of DockerOperator

Additional part:
- Implemented sensors that the data is ready for training and learning dags
- Alerts are configured in case of a dag crash

Required screenshots:
<img width="1413" alt="All_DAGs" src="https://user-images.githubusercontent.com/58679315/204397661-9ea9d887-9ac2-4d50-9ae9-b4bd67827673.png">
<img width="1409" alt="dag_download" src="https://user-images.githubusercontent.com/58679315/204397659-0e2ea8f3-f43f-4373-8dfd-f32cecbf0c1b.png">
<img width="1407" alt="dag_train" src="https://user-images.githubusercontent.com/58679315/204397650-a773692a-1dc3-4e7c-aee5-f34ea141afb2.png">
<img width="1410" alt="dag_predict" src="https://user-images.githubusercontent.com/58679315/204397655-85aaf053-eb44-4517-a90d-b7b3aa92d961.png">

2022-12-04 13:27 UTC, bulaevvi commented
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в **исполненном** без ошибок виде) и прикрепите их в описание пулл реквеста". На Ваших скриншотах train и predict узлы белые, т.е. формально задание не выполнено. На первом скриншоте также видно, что даги обучения и инференса не выполнены, т.к. они светлозеленые (в процессе выполнения), а должны быть темнозеленые

2022-12-04 13:31 UTC, bulaevvi requested changes
В задании указано: "Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в **исполненном** без ошибок виде) и прикрепите их в описание пулл реквеста". На Ваших скриншотах train и predict узлы белые, т.е. формально задание не выполнено. На первом скриншоте также видно, что даги обучения и инференса не выполнены, т.к. они светло-зеленые (в процессе выполнения), а должны быть темно-зеленые

2022-12-06 03:33 UTC, bulaevvi commented
См. пример скриншотов в дискорде https://discord.com/channels/681511874449244211/1011956997790380123/1049258596866727946

2022-12-25 15:15 UTC, AlexG888 commented
Владимир, добрый день! 
Прикладываю необходимые скриншоты:

<img width="1405" alt="Screenshot_all_dags" src="https://user-images.githubusercontent.com/58679315/209473304-806e725d-d45d-4bca-9b1d-da6bcc3b2cdf.png">
<img width="1394" alt="Screenshot_dag_download" src="https://user-images.githubusercontent.com/58679315/209473309-8e4a7065-0851-4aa8-8898-82dc8303e57b.png">
<img width="1401" alt="Screenshot_dag_predict" src="https://user-images.githubusercontent.com/58679315/209473310-fab9d560-14e3-4874-8d94-4537828c6ca1.png">
<img width="1400" alt="Screenshot_dag_train" src="https://user-images.githubusercontent.com/58679315/209473312-4f3b74fc-f979-4850-ad9e-427cdf5e49ef.png">

2022-12-26 03:02 UTC, bulaevvi approved these changes
Итого 38 баллов. Делайте merge или close

2022-12-26 05:26 UTC, merged